site_name: EQDSK Documentation
site_description: EQDSK, a python package for reading and writing eqdsk files
site_url: https://idk.com/
repo_name: Fusion-Power-Plant-Framework/eqdsk
repo_url: https://github.com/Fusion-Power-Plant-Framework/eqdsk
theme:
  name: material
watch:
  - eqdsk
plugins:
  - search
  - autorefs
  - gen-files:
      scripts:
        - scripts/gen_api_ref.py
  - literate-nav:
      nav_file: overview.md
  - mkdocstrings
nav:
  - index.md
  - examples.md
  - API Reference: reference/
