name: Lint EQDSk
on: [push]
jobs:
  lint:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup python and Hatch
        uses: "./.github/actions/setup-hatch"

      - name: Lint with ruff
        run: hatch run lint:all
