name: publish-docs

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  publish-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0

      - name: Configure Git Credentials
        run: |
          git config user.email "107038218+fppf-bot@users.noreply.github.com"
          git config user.name "fppf-bot"

      - name: Setup python and Hatch
        uses: Fusion-Power-Plant-Framework/fppf-actions/setup-hatch@c6af22fc8d00be67cca53a61177301462f499fb2

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Deploy documentation - publish to gh_pages
        run: hatch run docs:deploy --force
